[shell]
program = "ubuntu2204.exe"

[window]
opacity = 0.7
startup_mode = "Fullscreen"

[font]
normal = { family = "SauceCodePro Nerd Font" }
size = 14

[keyboard]
bindings = [{ key = "Space", mods = "Control", chars = "\u0000" }]
